package com.hillel.lecture_12;

public enum ConverterTypes {
    CELSIUSTOFAHRENHEIT,
    CELSIUSTOKELVIN,
    FAHRENHEITTOCELSIUS,
    INCHESTOMETERS,
    KILOGRAMSTOPOUNDS,
    KILOMETRESTOMILES,
    METERSTOOINCHES,
    MILESTOKILOMETRES,
    POUNDSTOKILOGRAMS,
    SPEEDKMTOMI,
    SPEEDMITOKM
}
